name: Build and Push Docker Image

on:
  push:
    branches: [ "docker-build" ]

env:
  IMAGE_NAME: lisiarend/prone.shiny # TODO: change image name

jobs:
  docker_build_push:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # TODO: add your Docker Hub username to your repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # TODO: add your Docker Hub password to your repository secrets
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
